### PR TITLE
Add GitHub Actions workflow that runs a test suite

### LINKED ISSUE #11: Automatically run our test suites on every push
via either CircleCI or GitHub Actions.

### PR DESCRIPTION
**Pull request by aviflax**
*the* test suite, really; we have only one so far.

Resolves #11

### CODE REVIEW

**Comment by mattsoutherden** [comment]
The pr that you helped @MarkReidFC rebase yesterday puts GitHub Actions for Ci into hold. 😱

**Comment by aviflax** [comment]
🤦‍♂️

**Comment by aviflax** [comment]
@mattsoutherden I’ve read the _hold_ recommendation in FundingCircle/docs#271 and the comments thereon. The only part of the rationale provided by  @FundingCircle/platform-architecture that makes sense to me is:

> GitHub Actions is not yet sufficiently mature for use as an enterprise CI/CD service, when compared to alternatives.

I’m not sure our technology recommendations should be based on comparisons of multiple technologies, but that’s a tangent, really.

More on point: I think that it would be reasonable for our open-source projects to not follow this recommendation. Presumably one of the reasons we release and maintain projects as open-source is to attract and enable contributions from third parties. I haven’t had a chance to fully articulate why, but I feel that GitHub Actions _is_ sufficiently mature for most of our open-source projects, which have simpler requirements than our internal projects. I also suspect that it might make a project a little more friendly to potential third-party contributors.

So: I think I’m going to suggest that we add an explicit exception to the recommendation for open-source projects. If that isn’t accepted, I might still choose to try GitHub Actions for now, but if so I suppose I should create an Architecture Decision Record that records and explains that decision.

What do you think?

----

/cc @robertstettner

**Comment by mattsoutherden** [comment]
I don't disagree, other than I'm not sure that GHA _is_ more friendly than CircleCI given the latter's ubiquity for open source projects over the last few years. Though that may change.

**Comment by aviflax** [comment]
> I don't disagree, other than I'm not sure that GHA _is_ more friendly than CircleCI given the latter's ubiquity for open source projects over the last few years. Though that may change.

Oh yeah, for sure, I agree that it’s iffy. But that’s _now_ — looking forward, I suspect that Actions will be friendlier and more accessible to potential contributors. The barrier to entry, to contributing to this project, is already quite high — a person would need a GitHub account, to be roughly familiar with how Git works, how GitHub Pull Requests work, etc. If someone wanted to contribute an improvement to an automation, I suspect that familiarizing themselves with, and learning to work with, Actions, would _feel_ less daunting for a large majority of that group of folks who are familiar with neither service.

Sorry if that didn’t make much sense… I’d be happy to jump on a video call and talk through it.

**Comment by aviflax** [comment]
🤔  Regardless of where we end up with our internal recommendation within Funding Circle, and/or other feedback from other reviewers, I’m inclined to merge this now because it would provide positive value now, and we might decide to just stick with it anyway. If we do decide to convert this to a CircleCI workflow, it’s not a big deal if we do it today, or in a week or two. And in the interim this incarnation of this workflow can provide some value.

Therefore I’m planning to merge this within a couple of hours, unless anyone objects.

**Comment by aviflax** [comment]
Ah, wait, I don’t have an approving review yet. So I’m going to hold off for now and hope to get one tomorrow.

**Comment by mattsoutherden** [comment]
I can approve if you like. I didn't before because you explicitly requested a review from @robertstettner

**Comment by robertstettner** [comment]
Hi guys,

Looking at the workflow, it is clear to me that GitHub Actions for CI/CD is not easy, and looks complex. I agree we would need to write up an ADR. I would also like to take this opportunity to showcase Drone to you all, and we have a use case too. :)

**Comment by robertstettner** [comment]
Regarding this PR, you have my approval. We should try Drone for this too.

**Comment by aviflax** [comment]
> …it is clear to me that GitHub Actions for CI/CD is not easy, and looks complex.

Interesting! That doesn’t jive with how I feel about it.

I can see how this specific job might give that impression at a glance, because there are a lot of lines related to caching. Those will be substantially reduced once the v2 version of the cache action is released. Apart from that, the other steps seem quite straightforward. 

Also, if there was a good container image somewhere that I could have used that would have included Clojure and been compatible with the cache action, the job would be even shorter. (I haven’t totally given up on finding such an image, just taking a break from it.)

This is something we can continue to look at and discuss over time, and we’ll see; maybe our assessments will converge.

> I agree we would need to write up an ADR.

👍

> I would also like to take this opportunity to showcase Drone to you all, and we have a use case too. :)

Sounds good! I do want to point out that even if Drone is a perfect fit for most of our projects, it might be a different story with our open-source projects, which have different requirements.

Thanks for the review!

**Pull request merged**
