### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by aviflax**
…mostly for maintainability.

* I suggest reviewing each commit individually
* I prefer to merge this one myself
* Thank you!

### CODE REVIEW

**Comment by mattsoutherden** [comment]
I'm not entirely convinced `c8e` is better than `confluence`.

**Comment by aviflax** [comment]
> I'm not entirely convinced `c8e` is better than `confluence`.

I hear you, but it’s all about context. In the context of this project, given its name, maybe it’s ok?

🤔 in general, I think elements of namespace _names_ should be fully spelled out, e.g. `md2c8e.confluence`. But namespace _aliases_ should, in general, be very short. In fact, in this case, I think `c` or `mc` would be serviceable as aliases, and might even be better than `c8e`.

What do you think? Should I change it to `c` or `mc`?

**Comment by aviflax** [comment]
Oh and thanks for the review!

**Comment by mattsoutherden** [comment]
Just visually scanning the file, it doesn't look to me like the alias `confluence` makes the text unwieldy, but - to me at least - it helps mentally juggle the code in my head when I don't have to also translate/map the alias.

**Comment by aviflax** [comment]
> Just visually scanning the file, it doesn't look to me like the alias `confluence` makes the text unwieldy, but - to me at least - it helps mentally juggle the code in my head when I don't have to also translate/map the alias.

I hear that. This seems to me like an example of the common tension between optimizing for regular maintainers who are well-versed in a codebase, and used to reading it, used to its quirks and conventions, versus accessibility to anyone less familiar with it.

In this case, `confluence` is a longer-than-usual namespace alias, which is slightly non-idiomatic for the Clojure community. Also, it makes lines of code longer, which necessitates maintainers thinking about where/how to break lines, which I’ve already found annoying to deal with in this codebase. (I can’t stand having to think about this sort of thing, but AFAIK the Clojure ecosystem does not yet have a viable opinionated code formatter akin to gofmt or Black. As soon as I find one I will eagerly adopt it.)

So, I’d like to use something shorter than `confluence`. I like `c8e` because it reinforces the abbreviation for “Confluence” which is already used in the project name, and it’s kinda cute too. But I have to admit it’s not easy on the eyes; something like `c` or `mc` would probably be better for readability and accessibility.

Do you think we should change this to `c` or `mc`? I’d be OK with that. If you’re on the fence, though, I’ll just leave this as-is.

Thanks!

**Comment by mattsoutherden** [comment]
Leave it. 👍

**Comment by aviflax** [comment]
😎 🙇

**Pull request merged**
